/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan_furniture;

import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Aplikasi_Data_Pesanan extends javax.swing.JDialog {
  koneksi kon = new koneksi();
  public Aplikasi_Barang_Masuk masuk = null;
private String tgl;
private Object [][] datapemesan=null;
private String[]labelpemesanan={"No Pemesanan","Kode Barang","Nama Barang","Deskripsi Barang","Nama Supplier","Alamat Supplier","Harga Beli","Jumlah","Subtotal"};
    /**
     * Creates new form Aplikasi_Data_Pesanan
     */
    public Aplikasi_Data_Pesanan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon ico = new ImageIcon("src/gambar/glj.png");
        setIconImage(ico.getImage());
         kon.setKoneksi();
         BacaTabelPesanan();
    }
private void BacaTabelPesanan(){
        try{
            String sql="Select *From detailpemesanan order by id_pemesanan";
            kon.rs=kon.st.executeQuery(sql);
             ResultSetMetaData m=kon.rs.getMetaData();
            int kolom=m.getColumnCount();
            int baris=0;
            while(kon.rs.next()){
                baris=kon.rs.getRow();
            }
            datapemesan= new Object[baris][kolom];
            int x=0;
            kon.rs.beforeFirst();
            while(kon.rs.next()){
              datapemesan[x][0]=kon.rs.getString("id_pemesanan");
               datapemesan[x][1]=kon.rs.getString("kd_brg");
                datapemesan[x][2]=kon.rs.getString("nm_brg");
                datapemesan[x][3]=kon.rs.getString("deskripsi");
                datapemesan[x][4]=kon.rs.getString("nm_sp");
                datapemesan[x][5]=kon.rs.getString("alamat");
                datapemesan[x][6]=kon.rs.getString("harga_beli");
                datapemesan[x][7]=kon.rs.getString("jumlah");
                datapemesan[x][8]=kon.rs.getString("subtotal");
                x++;
}
            Tbl_Pesanan.setModel(new DefaultTableModel(datapemesan,labelpemesanan));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void BacaTabelProdukCari()
    {
        try{
            String sql="Select *From detailpemesanan where id_pemesanan like '%" +tcari.getText()+"%'";
            kon.rs=kon.st.executeQuery(sql);
             ResultSetMetaData m=kon.rs.getMetaData();
            int kolom=m.getColumnCount();
            int baris=0;
            while(kon.rs.next()){
                baris=kon.rs.getRow();
            }
            datapemesan= new Object[baris][kolom];
            int x=0;
            kon.rs.beforeFirst();
            while(kon.rs.next()){
               datapemesan[x][0]=kon.rs.getString("id_pemesanan");
               datapemesan[x][1]=kon.rs.getString("kd_brg");
                datapemesan[x][2]=kon.rs.getString("nm_brg");
                datapemesan[x][3]=kon.rs.getString("deskripsi");
                datapemesan[x][4]=kon.rs.getString("nm_sp");
                datapemesan[x][5]=kon.rs.getString("alamat");
                datapemesan[x][6]=kon.rs.getString("harga_beli");
                datapemesan[x][7]=kon.rs.getString("jumlah");
                datapemesan[x][8]=kon.rs.getString("subtotal");
                x++;
}
            Tbl_Pesanan.setModel(new DefaultTableModel(datapemesan,labelpemesanan));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Pesanan = new javax.swing.JTable();
        tcari = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplikasi Data Pesanan");

        Tbl_Pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "null", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        Tbl_Pesanan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Tbl_Pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_PesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Pesanan);

        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcariKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tcariKeyTyped(evt);
            }
        });

        jLabel7.setText("Cari");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 113, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(379, 220));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tbl_PesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_PesananMouseClicked
        // TODO add your handling code here:
      int tabelBarang = Tbl_Pesanan.getSelectedRow();
      masuk.IdPemesanan =Tbl_Pesanan.getValueAt(tabelBarang, 0).toString();
      masuk.KodeBarang =Tbl_Pesanan.getValueAt(tabelBarang, 1).toString();
      masuk.NamaBarang = Tbl_Pesanan.getValueAt(tabelBarang, 2).toString();
      
        masuk.NamaSupplier = Tbl_Pesanan.getValueAt(tabelBarang, 4).toString();
        masuk.Deskripsi = Tbl_Pesanan.getValueAt(tabelBarang, 3).toString();
        masuk.Jumlah = Tbl_Pesanan.getValueAt(tabelBarang, 7).toString();
        
        this.dispose();
    }//GEN-LAST:event_Tbl_PesananMouseClicked

    private void tcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariKeyPressed

    private void tcariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyTyped
        // TODO add your handling code here:
        BacaTabelProdukCari();
    }//GEN-LAST:event_tcariKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Data_Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Data_Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Data_Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Data_Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Aplikasi_Data_Pesanan dialog = new Aplikasi_Data_Pesanan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbl_Pesanan;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tcari;
    // End of variables declaration//GEN-END:variables
}
